/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlmacenesRouteImport } from './routes/almacenes'
import { Route as AreaDeCafeRouteImport } from './routes/area-de-cafe'
import { Route as AsociarmeRouteImport } from './routes/asociarme'
import { Route as CafeRouteImport } from './routes/cafe'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as CooperativaRouteImport } from './routes/cooperativa'
import { Route as CoworkingRouteImport } from './routes/coworking'
import { Route as CreditoYCarteraRouteImport } from './routes/credito-y-cartera'
import { Route as HistoriaRouteImport } from './routes/historia'
import { Route as PicRouteImport } from './routes/pic'
import { Route as ServiciosRouteImport } from './routes/servicios'
import { Route as SostenibilidadRouteImport } from './routes/sostenibilidad'
import { Route as TiendasKahveRouteImport } from './routes/tiendas-kahve'
import { Route as LineaCreditoSlugRouteImport } from './routes/linea-credito.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlmacenesRoute = AlmacenesRouteImport.update({
  id: '/almacenes',
  path: '/almacenes',
  getParentRoute: () => rootRouteImport,
} as any)
const AreaDeCafeRoute = AreaDeCafeRouteImport.update({
  id: '/area-de-cafe',
  path: '/area-de-cafe',
  getParentRoute: () => rootRouteImport,
} as any)
const AsociarmeRoute = AsociarmeRouteImport.update({
  id: '/asociarme',
  path: '/asociarme',
  getParentRoute: () => rootRouteImport,
} as any)
const CafeRoute = CafeRouteImport.update({
  id: '/cafe',
  path: '/cafe',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const CooperativaRoute = CooperativaRouteImport.update({
  id: '/cooperativa',
  path: '/cooperativa',
  getParentRoute: () => rootRouteImport,
} as any)
const CoworkingRoute = CoworkingRouteImport.update({
  id: '/coworking',
  path: '/coworking',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditoYCarteraRoute = CreditoYCarteraRouteImport.update({
  id: '/credito-y-cartera',
  path: '/credito-y-cartera',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoriaRoute = HistoriaRouteImport.update({
  id: '/historia',
  path: '/historia',
  getParentRoute: () => rootRouteImport,
} as any)
const PicRoute = PicRouteImport.update({
  id: '/pic',
  path: '/pic',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosRoute = ServiciosRouteImport.update({
  id: '/servicios',
  path: '/servicios',
  getParentRoute: () => rootRouteImport,
} as any)
const SostenibilidadRoute = SostenibilidadRouteImport.update({
  id: '/sostenibilidad',
  path: '/sostenibilidad',
  getParentRoute: () => rootRouteImport,
} as any)
const TiendasKahveRoute = TiendasKahveRouteImport.update({
  id: '/tiendas-kahve',
  path: '/tiendas-kahve',
  getParentRoute: () => rootRouteImport,
} as any)
const LineaCreditoSlugRoute = LineaCreditoSlugRouteImport.update({
  id: '/linea-credito/$slug',
  path: '/linea-credito/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/almacenes': typeof AlmacenesRoute
  '/area-de-cafe': typeof AreaDeCafeRoute
  '/asociarme': typeof AsociarmeRoute
  '/cafe': typeof CafeRoute
  '/contacto': typeof ContactoRoute
  '/cooperativa': typeof CooperativaRoute
  '/coworking': typeof CoworkingRoute
  '/credito-y-cartera': typeof CreditoYCarteraRoute
  '/historia': typeof HistoriaRoute
  '/pic': typeof PicRoute
  '/servicios': typeof ServiciosRoute
  '/sostenibilidad': typeof SostenibilidadRoute
  '/tiendas-kahve': typeof TiendasKahveRoute
  '/linea-credito/$slug': typeof LineaCreditoSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/almacenes': typeof AlmacenesRoute
  '/area-de-cafe': typeof AreaDeCafeRoute
  '/asociarme': typeof AsociarmeRoute
  '/cafe': typeof CafeRoute
  '/contacto': typeof ContactoRoute
  '/cooperativa': typeof CooperativaRoute
  '/coworking': typeof CoworkingRoute
  '/credito-y-cartera': typeof CreditoYCarteraRoute
  '/historia': typeof HistoriaRoute
  '/pic': typeof PicRoute
  '/servicios': typeof ServiciosRoute
  '/sostenibilidad': typeof SostenibilidadRoute
  '/tiendas-kahve': typeof TiendasKahveRoute
  '/linea-credito/$slug': typeof LineaCreditoSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/almacenes': typeof AlmacenesRoute
  '/area-de-cafe': typeof AreaDeCafeRoute
  '/asociarme': typeof AsociarmeRoute
  '/cafe': typeof CafeRoute
  '/contacto': typeof ContactoRoute
  '/cooperativa': typeof CooperativaRoute
  '/coworking': typeof CoworkingRoute
  '/credito-y-cartera': typeof CreditoYCarteraRoute
  '/historia': typeof HistoriaRoute
  '/pic': typeof PicRoute
  '/servicios': typeof ServiciosRoute
  '/sostenibilidad': typeof SostenibilidadRoute
  '/tiendas-kahve': typeof TiendasKahveRoute
  '/linea-credito/$slug': typeof LineaCreditoSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/almacenes'
    | '/area-de-cafe'
    | '/asociarme'
    | '/cafe'
    | '/contacto'
    | '/cooperativa'
    | '/coworking'
    | '/credito-y-cartera'
    | '/historia'
    | '/pic'
    | '/servicios'
    | '/sostenibilidad'
    | '/tiendas-kahve'
    | '/linea-credito/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/almacenes'
    | '/area-de-cafe'
    | '/asociarme'
    | '/cafe'
    | '/contacto'
    | '/cooperativa'
    | '/coworking'
    | '/credito-y-cartera'
    | '/historia'
    | '/pic'
    | '/servicios'
    | '/sostenibilidad'
    | '/tiendas-kahve'
    | '/linea-credito/$slug'
  id:
    | '__root__'
    | '/'
    | '/almacenes'
    | '/area-de-cafe'
    | '/asociarme'
    | '/cafe'
    | '/contacto'
    | '/cooperativa'
    | '/coworking'
    | '/credito-y-cartera'
    | '/historia'
    | '/pic'
    | '/servicios'
    | '/sostenibilidad'
    | '/tiendas-kahve'
    | '/linea-credito/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlmacenesRoute: typeof AlmacenesRoute
  AreaDeCafeRoute: typeof AreaDeCafeRoute
  AsociarmeRoute: typeof AsociarmeRoute
  CafeRoute: typeof CafeRoute
  ContactoRoute: typeof ContactoRoute
  CooperativaRoute: typeof CooperativaRoute
  CoworkingRoute: typeof CoworkingRoute
  CreditoYCarteraRoute: typeof CreditoYCarteraRoute
  HistoriaRoute: typeof HistoriaRoute
  PicRoute: typeof PicRoute
  ServiciosRoute: typeof ServiciosRoute
  SostenibilidadRoute: typeof SostenibilidadRoute
  TiendasKahveRoute: typeof TiendasKahveRoute
  LineaCreditoSlugRoute: typeof LineaCreditoSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/almacenes': {
      id: '/almacenes'
      path: '/almacenes'
      fullPath: '/almacenes'
      preLoaderRoute: typeof AlmacenesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/area-de-cafe': {
      id: '/area-de-cafe'
      path: '/area-de-cafe'
      fullPath: '/area-de-cafe'
      preLoaderRoute: typeof AreaDeCafeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asociarme': {
      id: '/asociarme'
      path: '/asociarme'
      fullPath: '/asociarme'
      preLoaderRoute: typeof AsociarmeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cafe': {
      id: '/cafe'
      path: '/cafe'
      fullPath: '/cafe'
      preLoaderRoute: typeof CafeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cooperativa': {
      id: '/cooperativa'
      path: '/cooperativa'
      fullPath: '/cooperativa'
      preLoaderRoute: typeof CooperativaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coworking': {
      id: '/coworking'
      path: '/coworking'
      fullPath: '/coworking'
      preLoaderRoute: typeof CoworkingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credito-y-cartera': {
      id: '/credito-y-cartera'
      path: '/credito-y-cartera'
      fullPath: '/credito-y-cartera'
      preLoaderRoute: typeof CreditoYCarteraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historia': {
      id: '/historia'
      path: '/historia'
      fullPath: '/historia'
      preLoaderRoute: typeof HistoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pic': {
      id: '/pic'
      path: '/pic'
      fullPath: '/pic'
      preLoaderRoute: typeof PicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios': {
      id: '/servicios'
      path: '/servicios'
      fullPath: '/servicios'
      preLoaderRoute: typeof ServiciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sostenibilidad': {
      id: '/sostenibilidad'
      path: '/sostenibilidad'
      fullPath: '/sostenibilidad'
      preLoaderRoute: typeof SostenibilidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tiendas-kahve': {
      id: '/tiendas-kahve'
      path: '/tiendas-kahve'
      fullPath: '/tiendas-kahve'
      preLoaderRoute: typeof TiendasKahveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/linea-credito/$slug': {
      id: '/linea-credito/$slug'
      path: '/linea-credito/$slug'
      fullPath: '/linea-credito/$slug'
      preLoaderRoute: typeof LineaCreditoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlmacenesRoute: AlmacenesRoute,
  AreaDeCafeRoute: AreaDeCafeRoute,
  AsociarmeRoute: AsociarmeRoute,
  CafeRoute: CafeRoute,
  ContactoRoute: ContactoRoute,
  CooperativaRoute: CooperativaRoute,
  CoworkingRoute: CoworkingRoute,
  CreditoYCarteraRoute: CreditoYCarteraRoute,
  HistoriaRoute: HistoriaRoute,
  PicRoute: PicRoute,
  ServiciosRoute: ServiciosRoute,
  SostenibilidadRoute: SostenibilidadRoute,
  TiendasKahveRoute: TiendasKahveRoute,
  LineaCreditoSlugRoute: LineaCreditoSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
